version: '3.4'

services:
  web:
    build: 
      context: .
      network: host
    command: python Project_Based_Learning/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/PBL-server
    ports:
      - "8000:8000"
